// Curated inventory of every tombstone/non-interleaving test source found in:
// this repository, the adjacent checker/archive repositories, git history, and
// the Fugue project notes under ~/.claude.  This is presentation metadata only;
// executable outcomes still come from their source suites.

const row = (id, name, published, disposition, relation, reason) => ({
  id, name, published, disposition, relation, reason,
});

export const corpusAuditSections = [
  {
    source: "test_tombstone_invariance.js",
    note: "The 13 visualized candidates. Twelve gate the default suite; N6 remains executable with --include-excluded so its redundancy can be reviewed.",
    rows: [
      row("N1", "unseen insert-delete pair at document start", "FAIL", "main", "main diagram", "Smallest remote ghost-history witness."),
      row("N2", "minimal interior RO phantom barrier", "FAIL", "main", "main diagram", "Smallest interior reverse-RO witness."),
      row("N3", "original ABCD phantom-barrier figure", "FAIL", "main", "main diagram", "Exact assertion for the original paired-history figure."),
      row("N4", "left-child/right-child routing changes with a tombstone", "FAIL", "main", "main diagram", "Covers the branch that a next-live-RO-only patch never touches."),
      row("N5", "chain of unseen tombstones", "FAIL", "main", "main diagram", "Prevents a one-hop-only repair."),
      row("N6", "ghost moves a whole forward-typed run", "FAIL", "represented", "excluded duplicate", "Same placement mechanism as N3 plus C2's independent run-adjacency guard."),
      row("N7", "insert-before-delete versus delete-before-insert", "PASS", "control", "next-live-RO rejection", "Published FugueMax is correct here; retained because the naive live-RO patch fails it."),
      row("S1", "deleting an RO cannot reorder surviving siblings", "PASS", "control", "delete stability", "Rejects delete-time origin rewriting; it is not a published counterexample."),
      row("S2", "deletion-chain stability", "PASS", "control", "delete stability", "Rejects chain-hopping/replacement-RO fixes; published passes."),
      row("C1", "Figure 7 reverse-RO clumping", "PASS", "control", "paper behavior", "Protects the reason FugueMax uses reverse right-origin order."),
      row("C2", "forward continuation remains adjacent", "PASS", "control", "forward non-interleaving", "Published passes; current Era fails. This is the explicit guard against accepting APYQ."),
      row("C3", "tombstone with a live continuation remains meaningful", "PASS", "control", "referenced history", "Published passes; current Era fails. A live dependant means the tombstone is not disposable."),
      row("C4", "AYC slot order independent of sender IDs", "FAIL", "control", "exact-boundary control", "Both ops are side=L,parent/RO=B. C4 narrowly orders the already-occupied slot before the direct post-delete insert without adopting global Era separation."),
    ],
  },
  {
    source: "index.js",
    note: "The original mixed demo/regression script. Several functions print outcomes; only the later phantom-barrier block has assertions.",
    rows: [
      row("I1", "baseline b / a / x scenario", "not asserted", "exploratory", "none", "Delete-free smoke demonstration; it states no tombstone invariant."),
      row("I2", "Figure 7", "PASS", "represented", "C1", "The exact positive control is retained as C1."),
      row("I3", "ABCD Interleaving 1", "not asserted", "represented", "C1", "Larger delete-free reverse-RO example; C1 is its minimal asserted form."),
      row("I4", "ABCD Interleaving 2", "not asserted", "represented", "C1", "Alternate construction of the same delete-free clumping rule."),
      row("I5", "ABCD Deletion", "not asserted alone", "represented", "N3 history A", "One half of the original phantom-barrier comparison; N3 asserts it against Sync First."),
      row("I6", "ABCD Deletion (Sync First)", "not asserted alone", "represented", "N3 history B", "The other half of N3; neither half is meaningful as a neutrality test alone."),
      row("I7", "Concurrent DE between BC (bdac)", "expected behavior", "outside", "bdac", "Delete-free same-(LO,RO) ID ordering. Later analysis and the user concluded bdac is correct, not a tombstone defect."),
      row("I8", "PhantomBarrier_Basic", "PASS convergence", "represented", "N2/N3", "Compares delivery orders of one op-set, so it cannot assert paired-history neutrality; N2/N3 ask the stronger question."),
      row("I9", "PhantomBarrier_ChainDelete", "PASS convergence", "represented", "N5/S2", "Its chain geometry survives as N5; its delete-stability concern survives as S2."),
      row("I10", "PhantomBarrier_MultiPeerDelete", "PASS convergence", "represented", "S1/S2", "Useful delivery-order stress, but not a no-ghost versus ghost comparison."),
      row("I11", "ResortingConvergence", "PASS", "represented", "S1", "Pins convergence after delete; S1 states the stronger no-reordering requirement."),
      row("I12", "MaximalNonInterleaving hello/world", "PASS", "represented", "C1/C2/N6", "Delete-free run-contiguity smoke test; the distilled cases exercise the relevant boundaries."),
      row("I13", "DeletionConvergence", "PASS weak bound", "represented", "N3", "Only requires Y to remain somewhere between A and C, so AYZXCD and AZXYCD both pass. N3 restores exact equality."),
    ],
  },
  {
    source: "test_fig2.js",
    note: "One exploratory Figure-2 construction with three printed checks and no failing process status.",
    rows: [
      row("F2.1", "same visible intent with and without hidden b†", "not asserted", "represented", "N1/N2/N4", "It creates two different y operations and merges both into one document; it does not compare paired histories with the same surviving edits."),
      row("F2.2", "four independent witness delivery orders", "not asserted", "represented", "convergence controls", "Checks delivery convergence only; published FugueMax already guarantees this."),
      row("F2.3", "final RA/RB value equality", "not asserted", "represented", "convergence controls", "The comment mentions tree identity, but the code compares visible values only and never compares saves."),
    ],
  },
  {
    source: "test_lo.js",
    note: "Four print-only explorations that motivated later assertions.",
    rows: [
      row("LO1", "insert c then delete b versus delete b then insert c", "PASS", "represented", "N7", "N7 turns the live-RO failure into an exact assertion with the needed concurrent M witness."),
      row("LO2", "bdac", "expected behavior", "outside", "bdac", "No tombstone and no missing information with which to override the same-origin ID tie."),
      row("LO3", "LO-side phantom barrier: y after delete, z while b alive", "not asserted", "represented", "N4/C3", "N4 isolates the route change; C3 preserves the live continuation boundary."),
      row("LO4", "same logical slot, different tombstone visibility", "not asserted", "represented", "N4/C4", "N4 captures structural variance; C4 captures the sender-ID ordering consequence."),
    ],
  },
  {
    source: "test_lo2.js",
    note: "Longer print-only versions of operation-order divergence and bdac.",
    rows: [
      row("LO2.1", "Order 1 with concurrent xyz and w", "PASS convergence", "represented", "N7/C2", "The order-1 side is a control; it does not fail published FugueMax."),
      row("LO2.2", "Order 2 with concurrent xyz and w", "PASS convergence", "represented", "N7/N6", "N7 captures the operation-order hazard and N6 captures whole-run movement."),
      row("LO2.3", "bdac with one de run", "expected behavior", "outside", "bdac", "Delete-free and later accepted as correct same-origin ordering."),
      row("LO2.4", "bdac with de and fg runs", "expected behavior", "outside", "bdac", "Run-length extension of the same accepted delete-free case."),
    ],
  },
  {
    source: "test_solution.js",
    note: "All 32 Era-conformance assertions, individually audited against published FugueMax. ‘Disputed’ means the expected string is an Era design choice, not an already-agreed ghost-neutrality/non-interleaving invariant.",
    rows: [
      row("E01", "POINT 1: pre-era y,m,w before post-era n", "FAIL", "disputed", "N5/C3 family", "Asserts global era separation (aymwn), not paired-history neutrality; canonical gives aynmw."),
      row("E02", "AYC senders c=1,y=9", "FAIL", "represented", "C4", "C4 includes this failing sender assignment."),
      row("E03", "AYC senders c=9,y=1", "PASS", "represented", "C4", "C4 includes this mirror to prove the result must not be an ID lottery."),
      row("E04", "AYC senders c=5,y=0", "PASS", "represented", "C4", "Additional sender sample of the same C4 property."),
      row("E05", "Order 1 same-slot c,y convergence", "PASS", "control", "N7", "Same-knowledge operations legitimately use the ID tie; not a published failure."),
      row("E06", "Order 2 plus concurrent xyz,w converges", "PASS", "control", "N7/N6", "Delivery convergence only; retained in the Era suite."),
      row("E07", "xyz remains contiguous", "PASS", "control", "C2/N6", "Run-contiguity control; published passes."),
      row("E08", "right-side era, x=1,z=9 expects azx", "FAIL", "disputed", "era-only", "Canonical axz is forced by the paper's backward-NI geometry; azx adopts a new era exception."),
      row("E09", "right-side era, x=9,z=1 expects azx", "FAIL", "disputed", "era-only", "Sender mirror of E08; same specification conflict."),
      row("E10", "left-child era expects ayzxm", "FAIL", "disputed", "era-only", "Canonical axyzm follows the original structural rule; the expected order requires era re-anchoring."),
      row("E11", "phantom runs post=1,pre=9", "FAIL", "represented", "C4/N6 extension", "Run-sized sender-ID lottery; C4 is the minimal ordering witness and N6 covers run movement."),
      row("E12", "phantom runs post=9,pre=1", "PASS", "represented", "C4/N6 extension", "The lucky sender assignment paired with E11."),
      row("E13", "three stacked eras expects ayq", "FAIL", "disputed", "stacked C4 extension", "A useful extension, but the ayq expectation assumes Era layering rather than the original paired-history contract."),
      row("E14", "Figure 7 reverse-RO order", "PASS", "represented", "C1", "Exact retained control."),
      row("E15", "two post-era runs converge", "PASS", "control", "C2", "Convergence-only run stress."),
      row("E16", "both post-era runs remain contiguous", "PASS", "control", "C2", "Published already preserves both runs."),
      row("E17", "UWZX without unrelated w sync expects zxwe", "FAIL", "disputed", "era-only", "Requires era to override reverse-RO/backward NI; not implied by the original target."),
      row("E18", "UWZX after syncing unrelated w expects zxwe", "FAIL", "disputed", "era-only", "Sync-robust mirror of E17; valuable if Era semantics are chosen."),
      row("E19", "POINT1-minus-m expects aywn", "FAIL", "disputed", "conflicts C2", "SOLUTION.md explicitly accepts that aywn overrides forward non-interleaving; the current review does not assume that override."),
      row("E20", "payload synchrony across four generation histories", "PASS", "control", "N7 / payload", "Checks byte-level op identity, not final visible ordering; published already passes."),
      row("E21", "T1 y=9 expects apyq", "FAIL", "disputed", "directly conflicts C2", "APYQ splits P→Q despite LO(Q)=P; this is the exact normative conflict raised by the user."),
      row("E22", "T1 y=0 expects aypq", "PASS", "control", "C2", "AYPQ is one of C2's two adjacency-preserving outcomes."),
      row("E23", "T1′ author saw y before backspace", "PASS", "control", "observed dependency", "Here y was genuinely observed, so APYQ is not a ghost-history witness."),
      row("E24", "T3 batched delete+insert expects ayc", "FAIL", "represented", "C4 batching variant", "Same C4 lottery in one transaction. It remains in the Era suite; a dedicated batching regression is still worth adding."),
      row("E25", "T4 batched inserts into dead gap", "PASS", "control", "batching", "Same-transaction causal-order control, not a published counterexample."),
      row("E26", "corollary (iv), x=1 expects axB", "PASS", "control", "origin-order", "Both outcomes are explicitly allowed by concurrent intent."),
      row("E27", "corollary (iv), x=9 expects aBx", "PASS", "control", "origin-order", "Sender mirror of E26."),
      row("E28", "corollary (iii+iv), x=1 expects avxB", "PASS", "control", "descendant pin", "Protects an explicit v-before-x dependency; published passes."),
      row("E29", "corollary (iii+iv), x=9 expects aBvx", "PASS", "control", "descendant pin", "Sender mirror of E28."),
      row("E30", "T8 multi-stop pins expects a1m2n3", "FAIL", "disputed", "era pin semantics", "A receiver-era placement requirement, not yet derived from the original ghost-neutrality contract."),
      row("E31", "T9 explicit pin override expects axy", "PASS", "control", "origin-order", "Published respects the explicit before-y insertion."),
      row("E32", "T10 backward post-era run expects ay789m", "FAIL", "disputed", "era-only", "Canonical a789ym keeps 789 contiguous; the failure is era order, not run interleaving."),
    ],
  },
  {
    source: "model_check.js",
    note: "Seven randomized properties over plain, ghosted, and prune-barrier traces. These are property families, not a finite list of hand-authored cases.",
    rows: [
      row("MC1", "era separation", "often FAIL", "disputed", "C4/Era suite", "Tests the Era axiom across random traces; it is not equivalent to ghost neutrality."),
      row("MC2", "prune neutrality", "FAIL seeds", "represented", "N1–N6", "The paired-history target at scale; N1–N6 are readable reductions, while the randomized check remains valuable."),
      row("MC3", "ghost neutrality", "FAIL seeds", "represented", "N1", "N1 is the smallest durable reduction; the checker explores broader random contexts."),
      row("MC4", "origin order", "PASS", "control", "strong-list sanity", "Rejects edits crossing their generation-time visible neighbors."),
      row("MC5", "step stability", "PASS", "control", "S1/S2", "Rejects delivery or deletion reordering already-visible characters."),
      row("MC6", "run interleaving", "PASS", "control", "C1/C2/N6", "Rejects alternating peer runs; whole-block nesting remains allowed."),
      row("MC7", "delivery convergence (opt-in)", "PASS", "control", "convergence", "Useful against experimental state-dependent fixes, but not the semantic-variance property itself."),
    ],
  },
  {
    source: "../collaborative-text-editing-algorithms/code/tombstone_checker",
    note: "Adjacent-repository randomized tombstone tests found during the expanded audit. These were not counted in the original 13-case page.",
    rows: [
      row("PY1", "step stability: 30 seeds × Fugue/FugueMax/RGA/Yjs", "PASS", "control", "S1/S2", "Broad cross-algorithm stability check; not a paired-history failure."),
      row("PY2", "origin order: 30 seeds × Fugue/FugueMax/RGA/Yjs", "PASS", "control", "origin-order", "Broad strong-list sanity check."),
      row("PY3", "delivery variants: 10 seeds × Fugue/FugueMax × 20 replays", "PASS", "control", "convergence", "Tests schedule independence only."),
      row("PY4", "WOOT ghost neutrality: 10 seeds", "PASS", "control", "cross-algorithm baseline", "Demonstrates that the checker can pass an algorithm without Fugue's phantom barrier."),
      row("PY5", "seed 2 detects Fugue and FugueMax phantom barrier", "FAIL as intended", "represented", "N1", "Random witness whose ghost becomes a concurrent insert's parent; N1 is the readable minimal reduction."),
    ],
  },
  {
    source: "../dissertation interleaving/list-spec checkers",
    note: "Adjacent research checkers inspected because earlier Fugue work referred to them. Their trace generators deliberately disable deletes, so they cannot validate tombstone semantics.",
    rows: [
      row("DS1", "random interleaving traces", "insert-only", "outside", "none", "with_deletes=False; cannot create a phantom barrier or exercise a tombstoned origin."),
      row("DS2", "exhaustive interleaving traces", "insert-only", "outside", "none", "Also disables deletes; useful for the paper's original non-interleaving property only."),
      row("DS3", "forward/backward non-interleaving oracle", "tombstone-blind", "outside", "C1/C2", "Indexes origins in visible state and crashes or misclassifies when origins are deleted; unsuitable as a tombstone oracle."),
      row("DS4", "random/exhaustive strong-list-spec checks", "insert-only", "control", "MC4", "Useful origin-order background, but no delete history is generated."),
      row("DS5", "list-spec example fixtures", "insert-only", "outside", "none", "Specification examples, not FugueMax tombstone regressions."),
    ],
  },
  {
    source: "crdt-benchmarks",
    note: "All benchmark scenario families. They measure runtime, update size, memory, encoding, document size, and parsing; none assert a semantic final ordering.",
    rows: [
      row("B1.1", "append N characters", "not semantic", "outside", "performance", "No competing history or expected visible order."),
      row("B1.2", "insert one string of length N", "not semantic", "outside", "performance", "Bulk-insert throughput/size benchmark."),
      row("B1.3", "prepend N characters", "not semantic", "outside", "performance", "Sequential performance benchmark."),
      row("B1.4", "insert N characters at random positions", "not semantic", "outside", "performance", "Random edit performance, not a fixed counterexample."),
      row("B1.5", "insert N words at random positions", "not semantic", "outside", "performance", "Word-granularity performance only."),
      row("B1.6", "insert a string, then delete it", "not semantic", "outside", "performance", "Contains tombstones but records cost/size only; no later concurrent edit tests neutrality."),
      row("B1.7", "random-position string inserts/deletes", "not semantic", "outside", "performance", "Delete workload without a semantic oracle."),
      row("B1.8", "append N numbers", "not semantic", "outside", "performance", "Value-type performance variant."),
      row("B1.9", "insert an array of N numbers", "not semantic", "outside", "performance", "Bulk numeric performance variant."),
      row("B1.10", "prepend N numbers", "not semantic", "outside", "performance", "Numeric prepend performance variant."),
      row("B1.11", "insert N numbers at random positions", "not semantic", "outside", "performance", "Numeric random-position performance variant."),
      row("B2.1", "two clients concurrently insert a length-N string at index 0", "not semantic", "outside", "performance", "Concurrent workload, but the harness reports cost rather than checking a required ordering."),
      row("B2.2", "concurrently insert N characters at random positions", "not semantic", "outside", "performance", "Concurrency stress without a tombstone property assertion."),
      row("B2.3", "concurrently insert N words at random positions", "not semantic", "outside", "performance", "Concurrency throughput/space benchmark."),
      row("B2.4", "concurrent insert and delete", "not semantic", "outside", "performance", "Relevant workload shape, but no paired-history or non-interleaving oracle."),
      row("B3.4", "20√N clients concurrently insert text", "not semantic", "outside", "performance", "Many-client scaling benchmark."),
      row("B4", "apply real-world editing dataset", "not semantic", "outside", "performance", "Replays a dataset for cost metrics; does not declare which visible order is correct."),
      row("B4×100", "apply real-world dataset 100 times", "not semantic", "outside", "performance", "Scale amplification of B4."),
    ],
  },
  {
    source: "yjs-interleave/index.js and historical workspace copies",
    note: "Other nearby Fugue-related scripts and copies checked for unique scenarios.",
    rows: [
      row("Y1", "Yjs b / a / x baseline", "not asserted", "outside", "I1 analogue", "Delete-free one-line comparison; prints axb and contains no phantom-barrier property."),
      row("H1", "../tree-borrows/fugue/fugue-interleave/index.js", "duplicate", "represented", "I1–I7", "Historical copy of the early index.js scenarios; no unique case was found."),
    ],
  },
  {
    source: "correspondence and project documents",
    note: "Named scenarios in the archived emails, PROBLEM.md, slides.md, and SOLUTION.md. They are aliases/specification claims rather than additional executable tests.",
    rows: [
      row("D1", "email concern 1 / Figure-7 degree of freedom", "not a test", "represented", "C1", "Resolved as a required reverse-RO control, not a tombstone counterexample."),
      row("D2", "email concern 2 / phantom barrier figure", "FAIL", "represented", "N3", "The attached ABCD figure is N3."),
      row("D3", "email concern 3 / same-LO different-RO freedom", "not a test", "represented", "C1", "Later theorem review established reverse-RO is forced."),
      row("D4", "reply: order-1 versus order-2 tree divergence", "mixed", "represented", "N7", "N7 preserves the concrete failure of the proposed next-live-RO fix."),
      row("D5", "reply: bdac", "expected behavior", "outside", "bdac", "Later explicitly withdrawn as a bug claim."),
      row("D6", "PROBLEM.md Problem 1: delete-time RO shifting", "old fix failed", "represented", "S1/S2", "Historical old-fix problem; current implementation no longer uses replacementRightOrigin."),
      row("D7", "PROBLEM.md Problem 2: LO phantom route", "FAIL", "represented", "N4", "N4 is the minimal executable form; the document's proposed ‘as if b did not exist’ remedy is not assumed."),
      row("D8", "slides Part 6 AXYZCD expectation", "disputed", "disputed", "N3/C1", "The expected AXYZCD came from the old live-RO framing; N3 now asserts only paired-history equality while C1 preserves reverse-RO."),
      row("D9", "SOLUTION.md G1–G5 / O1–O4 / Definition 4′", "mixed", "disputed", "E01–E32", "These claims are exactly what test_solution.js tests; they are not independent evidence for choosing Era semantics."),
    ],
  },
  {
    source: "~/.claude Fugue memory and vanished /tmp scratch artifacts",
    note: "Scenarios recorded in research memory. Entries marked missing are not durable executable regressions in this workspace and therefore must not be silently counted as covered.",
    rows: [
      row("M1", "three-variant AYC comparison", "canonical FAIL", "represented", "C4", "Durable C4 reproduces the relevant sender lottery."),
      row("M2", "three-variant POINT 1 comparison", "canonical FAIL Era expectation", "disputed", "E01", "Preserved only in the Era conformance suite."),
      row("M3", "operation-order payload identity", "PASS", "represented", "N7/E20", "N7 covers visible consequences; E20 covers byte identity."),
      row("M4", "order-diverge aymc versus aycm", "live-RO FAIL", "represented", "N7", "This is the concrete next-live-RO rejection."),
      row("M5", "same visible state with/without synced delete", "Era payload differs in old build", "represented", "N4/E20", "Structural variance and payload synchrony are both retained."),
      row("M6", "S7 / UWZX sync-state flip", "canonical fixed; old Era generation FAIL", "represented", "E17/E18", "Durable in test_solution, but its expected zxwe remains an Era-specific choice."),
      row("M7", "T5 layered-stop chains", "scratch only", "represented", "E30 / T8", "The later durable T8 multi-stop test preserves the same pin-versus-layering obligation."),
      row("M8", "T6 concurrent double-delete", "scratch only", "missing", "C4 multi-delete extension", "No new ordering axiom beyond C4, but no durable regression checks that multiple delete dots leave the exact-boundary rule unchanged."),
      row("M9", "document-start geometry", "scratch only", "represented", "N1", "N1 is the durable minimal document-start case."),
      row("M10", "whole-document deletes plus concurrent typing", "scratch recovered", "disputed", "global Era composition", "The recovered yzx expectation globally orders pre/post-deletion eras across several boundaries; it is not implied by the retained narrow rules."),
      row("M11", "interleaved tombstone chains", "scratch only", "missing", "chain stress", "N5 covers a consecutive chain, but the vanished interleaved-chain trace is not durably reproduced."),
      row("M12", "three concurrent deleters", "scratch recovered", "represented", "C4 multi-delete extension", "Same exact-boundary rule as C4 with redundant delete dots; useful implementation stress, not a distinct semantic requirement."),
      row("M13", "walk across a 10-node concurrent subtree", "scratch recovered", "outside", "complexity stress", "Tests the abandoned Era receiver walk's traversal and cost, not a FugueMax ordering requirement."),
      row("M14", "save/load session boundaries and post-load causal entries", "scratch only", "missing", "persistence", "Important implementation regression: the current durable suites do not verify that a candidate preserves deletion knowledge and placement across save/load."),
      row("M15", "canonical parent/rightOrigin points at a concurrent node", "scratch recovered", "outside", "Era receiver plumbing", "Exercises the abandoned causal receiver-walk implementation, not a semantic property of the final algorithm."),
      row("M16", "deleted-left-origin family: ycb, vwmb pin, ycd composition (11 checks)", "scratch summary only", "disputed", "global Era symmetry", "These expected strings apply G3 era separation symmetrically to a crossed left boundary. That global Era axiom is not part of the retained specification."),
      row("M17", "300 randomized save/load runs", "scratch only", "missing", "persistence fuzz", "Reported as passing, but no durable randomized persistence runner remains."),
      row("M18", "1,200 randomized local-echo comparisons", "scratch only", "missing", "local echo", "Reported as passing, but no durable check compares every originator with a fresh merge."),
      row("M19", "F3 / strong-list randomized conformance", "scratch only", "missing", "strong-list fuzz", "The current model checker has origin-order sanity, but the vanished full conformance oracle is not durably reproduced."),
    ],
  },
];

export const corpusAuditCounts = corpusAuditSections.reduce((counts, section) => {
  counts.sources++;
  counts.rows += section.rows.length;
  for (const item of section.rows) counts[item.disposition] = (counts[item.disposition] ?? 0) + 1;
  return counts;
}, { sources: 0, rows: 0 });
